export const countries = [
  { label: 'Afghanistan', value: 'af', currencySymbol: '؋' },
  { label: 'Albania', value: 'al', currencySymbol: 'L' },
  { label: 'Algeria', value: 'dz', currencySymbol: 'دج' },
  { label: 'Andorra', value: 'ad', currencySymbol: '€' },
  { label: 'Angola', value: 'ao', currencySymbol: 'Kz' },
  { label: 'Antigua and Barbuda', value: 'ag', currencySymbol: '$' },
  { label: 'Argentina', value: 'ar', currencySymbol: '$' },
  { label: 'Armenia', value: 'am', currencySymbol: '֏' },
  { label: 'Australia', value: 'au', currencySymbol: '$' },
  { label: 'Austria', value: 'at', currencySymbol: '€' },
  { label: 'Azerbaijan', value: 'az', currencySymbol: '₼' },
  { label: 'Bahamas', value: 'bs', currencySymbol: '$' },
  { label: 'Bahrain', value: 'bh', currencySymbol: '.د.ب' },
  { label: 'Bangladesh', value: 'bd', currencySymbol: '৳' },
  { label: 'Barbados', value: 'bb', currencySymbol: '$' },
  { label: 'Belarus', value: 'by', currencySymbol: 'Br' },
  { label: 'Belgium', value: 'be', currencySymbol: '€' },
  { label: 'Belize', value: 'bz', currencySymbol: '$' },
  { label: 'Benin', value: 'bj', currencySymbol: 'CFA' },
  { label: 'Bhutan', value: 'bt', currencySymbol: 'Nu.' },
  { label: 'Bolivia', value: 'bo', currencySymbol: 'Bs.' },
  { label: 'Bosnia and Herzegovina', value: 'ba', currencySymbol: 'KM' },
  { label: 'Botswana', value: 'bw', currencySymbol: 'P' },
  { label: 'Brazil', value: 'br', currencySymbol: 'R$' },
  { label: 'Brunei', value: 'bn', currencySymbol: '$' },
  { label: 'Bulgaria', value: 'bg', currencySymbol: 'лв' },
  { label: 'Burkina Faso', value: 'bf', currencySymbol: 'CFA' },
  { label: 'Burundi', value: 'bi', currencySymbol: 'FBu' },
  { label: 'Cambodia', value: 'kh', currencySymbol: '៛' },
  { label: 'Cameroon', value: 'cm', currencySymbol: 'CFA' },
  { label: 'Canada', value: 'ca', currencySymbol: '$' },
  { label: 'Cape Verde', value: 'cv', currencySymbol: '$' },
  { label: 'Central African Republic', value: 'cf', currencySymbol: 'CFA' },
  { label: 'Chad', value: 'td', currencySymbol: 'CFA' },
  { label: 'Chile', value: 'cl', currencySymbol: '$' },
  { label: 'China', value: 'cn', currencySymbol: '¥' },
  { label: 'Colombia', value: 'co', currencySymbol: '$' },
  { label: 'Comoros', value: 'km', currencySymbol: 'CF' },
  { label: 'Congo (Brazzaville)', value: 'cg', currencySymbol: 'CFA' },
  { label: 'Congo (Kinshasa)', value: 'cd', currencySymbol: 'FC' },
  { label: 'Costa Rica', value: 'cr', currencySymbol: '₡' },
  { label: 'Croatia', value: 'hr', currencySymbol: '€' },
  { label: 'Cuba', value: 'cu', currencySymbol: '$' },
  { label: 'Cyprus', value: 'cy', currencySymbol: '€' },
  { label: 'Czech Republic', value: 'cz', currencySymbol: 'Kč' },
  { label: 'Denmark', value: 'dk', currencySymbol: 'kr' },
  { label: 'Djibouti', value: 'dj', currencySymbol: 'Fdj' },
  { label: 'Dominica', value: 'dm', currencySymbol: '$' },
  { label: 'Dominican Republic', value: 'do', currencySymbol: '$' },
  { label: 'Ecuador', value: 'ec', currencySymbol: '$' },
  { label: 'Egypt', value: 'eg', currencySymbol: '£' },
  { label: 'El Salvador', value: 'sv', currencySymbol: '$' },
  { label: 'Equatorial Guinea', value: 'gq', currencySymbol: 'CFA' },
  { label: 'Eritrea', value: 'er', currencySymbol: 'Nfk' },
  { label: 'Estonia', value: 'ee', currencySymbol: '€' },
  { label: 'Eswatini', value: 'sz', currencySymbol: 'E' },
  { label: 'Ethiopia', value: 'et', currencySymbol: 'Br' },
  { label: 'Fiji', value: 'fj', currencySymbol: '$' },
  { label: 'Finland', value: 'fi', currencySymbol: '€' },
  { label: 'France', value: 'fr', currencySymbol: '€' },
  { label: 'Gabon', value: 'ga', currencySymbol: 'CFA' },
  { label: 'Gambia', value: 'gm', currencySymbol: 'D' },
  { label: 'Georgia', value: 'ge', currencySymbol: '₾' },
  { label: 'Germany', value: 'de', currencySymbol: '€' },
  { label: 'Ghana', value: 'gh', currencySymbol: '₵' },
  { label: 'Greece', value: 'gr', currencySymbol: '€' },
  { label: 'Grenada', value: 'gd', currencySymbol: '$' },
  { label: 'Guatemala', value: 'gt', currencySymbol: 'Q' },
  { label: 'Guinea', value: 'gn', currencySymbol: 'FG' },
  { label: 'Guinea-Bissau', value: 'gw', currencySymbol: 'CFA' },
  { label: 'Guyana', value: 'gy', currencySymbol: '$' },
  { label: 'Haiti', value: 'ht', currencySymbol: 'G' },
  { label: 'Honduras', value: 'hn', currencySymbol: 'L' },
  { label: 'Hungary', value: 'hu', currencySymbol: 'Ft' },
  { label: 'Iceland', value: 'is', currencySymbol: 'kr' },
  { label: 'India', value: 'in', currencySymbol: '₹' },
  { label: 'Indonesia', value: 'id', currencySymbol: 'Rp' },
  { label: 'Iran', value: 'ir', currencySymbol: '﷼' },
  { label: 'Iraq', value: 'iq', currencySymbol: 'ع.د' },
  { label: 'Ireland', value: 'ie', currencySymbol: '€' },
  { label: 'Israel', value: 'il', currencySymbol: '₪' },
  { label: 'Italy', value: 'it', currencySymbol: '€' },
  { label: 'Jamaica', value: 'jm', currencySymbol: '$' },
  { label: 'Japan', value: 'jp', currencySymbol: '¥' },
  { label: 'Jordan', value: 'jo', currencySymbol: 'د.ا' },
  { label: 'Kazakhstan', value: 'kz', currencySymbol: '₸' },
  { label: 'Kenya', value: 'ke', currencySymbol: 'KSh' },
  { label: 'Kuwait', value: 'kw', currencySymbol: 'د.ك' },
  { label: 'Kyrgyzstan', value: 'kg', currencySymbol: 'с' },
  { label: 'Laos', value: 'la', currencySymbol: '₭' },
  { label: 'Latvia', value: 'lv', currencySymbol: '€' },
  { label: 'Lebanon', value: 'lb', currencySymbol: 'ل.ل' },
  { label: 'Lesotho', value: 'ls', currencySymbol: 'L' },
  { label: 'Liberia', value: 'lr', currencySymbol: '$' },
  { label: 'Libya', value: 'ly', currencySymbol: 'ل.د' },
  { label: 'Liechtenstein', value: 'li', currencySymbol: 'CHF' },
  { label: 'Lithuania', value: 'lt', currencySymbol: '€' },
  { label: 'Luxembourg', value: 'lu', currencySymbol: '€' },
  { label: 'Madagascar', value: 'mg', currencySymbol: 'Ar' },
  { label: 'Malawi', value: 'mw', currencySymbol: 'MK' },
  { label: 'Malaysia', value: 'my', currencySymbol: 'RM' },
  { label: 'Maldives', value: 'mv', currencySymbol: 'Rf' },
  { label: 'Mali', value: 'ml', currencySymbol: 'CFA' },
  { label: 'Malta', value: 'mt', currencySymbol: '€' },
  { label: 'Mauritania', value: 'mr', currencySymbol: 'UM' },
  { label: 'Mauritius', value: 'mu', currencySymbol: '₨' },
  { label: 'Mexico', value: 'mx', currencySymbol: '$' },
  { label: 'Moldova', value: 'md', currencySymbol: 'L' },
  { label: 'Monaco', value: 'mc', currencySymbol: '€' },
  { label: 'Mongolia', value: 'mn', currencySymbol: '₮' },
  { label: 'Montenegro', value: 'me', currencySymbol: '€' },
  { label: 'Morocco', value: 'ma', currencySymbol: 'د.م.' },
  { label: 'Mozambique', value: 'mz', currencySymbol: 'MT' },
  { label: 'Namibia', value: 'na', currencySymbol: '$' },
  { label: 'Nepal', value: 'np', currencySymbol: '₨' },
  { label: 'Netherlands', value: 'nl', currencySymbol: '€' },
  { label: 'New Zealand', value: 'nz', currencySymbol: '$' },
  { label: 'Nicaragua', value: 'ni', currencySymbol: 'C$' },
  { label: 'Niger', value: 'ne', currencySymbol: 'CFA' },
  { label: 'Nigeria', value: 'ng', currencySymbol: '₦' },
  { label: 'North Korea', value: 'kp', currencySymbol: '₩' },
  { label: 'Norway', value: 'no', currencySymbol: 'kr' },
  { label: 'Oman', value: 'om', currencySymbol: 'ر.ع.' },
  { label: 'Pakistan', value: 'pk', currencySymbol: '₨' },
  { label: 'Panama', value: 'pa', currencySymbol: '$' },
  { label: 'Paraguay', value: 'py', currencySymbol: '₲' },
  { label: 'Peru', value: 'pe', currencySymbol: 'S/' },
  { label: 'Philippines', value: 'ph', currencySymbol: '₱' },
  { label: 'Poland', value: 'pl', currencySymbol: 'zł' },
  { label: 'Portugal', value: 'pt', currencySymbol: '€' },
  { label: 'Qatar', value: 'qa', currencySymbol: 'ر.ق' },
  { label: 'Romania', value: 'ro', currencySymbol: 'lei' },
  { label: 'Russia', value: 'ru', currencySymbol: '₽' },
  { label: 'Rwanda', value: 'rw', currencySymbol: 'RWF' },
  { label: 'Saudi Arabia', value: 'sa', currencySymbol: 'ر.س' },
  { label: 'Senegal', value: 'sn', currencySymbol: 'CFA' },
  { label: 'Serbia', value: 'rs', currencySymbol: 'дин.' },
  { label: 'Seychelles', value: 'sc', currencySymbol: '₨' },
  { label: 'Sierra Leone', value: 'sl', currencySymbol: 'Le' },
  { label: 'Singapore', value: 'sg', currencySymbol: '$' },
  { label: 'Slovakia', value: 'sk', currencySymbol: '€' },
  { label: 'Slovenia', value: 'si', currencySymbol: '€' },
  { label: 'Somalia', value: 'so', currencySymbol: 'S' },
  { label: 'South Africa', value: 'za', currencySymbol: 'R' },
  { label: 'South Korea', value: 'kr', currencySymbol: '₩' },
  { label: 'Spain', value: 'es', currencySymbol: '€' },
  { label: 'Sri Lanka', value: 'lk', currencySymbol: '₨' },
  { label: 'Sudan', value: 'sd', currencySymbol: 'ج.س.' },
  { label: 'Sweden', value: 'se', currencySymbol: 'kr' },
  { label: 'Switzerland', value: 'ch', currencySymbol: 'CHF' },
  { label: 'Syria', value: 'sy', currencySymbol: '£' },
  { label: 'Taiwan', value: 'tw', currencySymbol: 'NT$' },
  { label: 'Tajikistan', value: 'tj', currencySymbol: 'ЅМ' },
  { label: 'Tanzania', value: 'tz', currencySymbol: 'TSh' },
  { label: 'Thailand', value: 'th', currencySymbol: '฿' },
  { label: 'Togo', value: 'tg', currencySymbol: 'CFA' },
  { label: 'Tonga', value: 'to', currencySymbol: 'T$' },
  { label: 'Trinidad and Tobago', value: 'tt', currencySymbol: '$' },
  { label: 'Tunisia', value: 'tn', currencySymbol: 'د.ت' },
  { label: 'Turkey', value: 'tr', currencySymbol: '₺' },
  { label: 'Turkmenistan', value: 'tm', currencySymbol: 'm' },
  { label: 'Uganda', value: 'ug', currencySymbol: 'USh' },
  { label: 'Ukraine', value: 'ua', currencySymbol: '₴' },
  { label: 'United Arab Emirates', value: 'ae', currencySymbol: 'د.إ' },
  { label: 'United Kingdom', value: 'gb', currencySymbol: '£' },
  { label: 'United States', value: 'us', currencySymbol: '$' },
  { label: 'Uruguay', value: 'uy', currencySymbol: '$' },
  { label: 'Uzbekistan', value: 'uz', currencySymbol: "so'm" },
  { label: 'Venezuela', value: 've', currencySymbol: 'Bs.' },
  { label: 'Vietnam', value: 'vn', currencySymbol: '₫' },
  { label: 'Yemen', value: 'ye', currencySymbol: '﷼' },
  { label: 'Zambia', value: 'zm', currencySymbol: 'ZK' },
  { label: 'Zimbabwe', value: 'zw', currencySymbol: 'Z$' },
].map((c) => ({
  ...c,
  requiredFields: ['stateOrProvince', 'city', 'street'],
  fieldLabels: {
    stateOrProvince: 'State/Province',
    city: 'City',
    street: 'Street Address',
  },
})).sort((a, b) => a.label.localeCompare(b.label));
